######## LIBRARIES USED ########
# not all libraries are used, some of them are just for full paper
library(foreign)
library(dplyr)
library(car)
library(Cairo)
library(corrplot)
library(effects)
library(ggplot2)
library(GGally)
library(psych)
library(Amelia)
library(MASS)
library(gvlma)
library(rms)
library(coefplot)
library(AER)
library(tidyr)
library(reshape2)
library(scales)
library(RColorBrewer)
library(gridExtra)
library(grid)
library(tidyr)
library(broom)
library(margins)
library(socviz)
library(here)

